#!/command/with-contenv bash

cd "${HOME}" || { echo "ERROR: failed to cd to ${HOME}"; exit 1; }

echo "INFO: starting websocket-ssh-proxy..."
exec 2>&1

exec s6-setuidgid ${NB_USER} /opt/ssh-proxy-venv/bin/python /opt/ssh-proxy/server.py
