# Development/testing targets for ssh-proxy-custom

.PHONY: test-build test-venv test clean

TEST_VENV := venv

test-build:
	REGISTRY=local TAG=test $(MAKE) docker-build-dep

test-venv:
	python3 -m venv $(TEST_VENV) && \
	$(TEST_VENV)/bin/pip install --quiet -r tests/requirements-test.txt

test: test-venv
	$(TEST_VENV)/bin/pytest tests/ -v

clean:
	rm -rf $(TEST_VENV)