# Development/testing targets for ssh-proxy-custom

.PHONY: test-build test-venv test clean

TEST_VENV := venv

test-build:
	REGISTRY=local TAG=test $(MAKE) docker-build-dep

test-venv:
	uv venv $(TEST_VENV) && \
	VIRTUAL_ENV=$(TEST_VENV) uv pip install --quiet -r tests/requirements-test.txt

test: test-venv
	$(TEST_VENV)/bin/pytest tests/ -v

clean:
	rm -rf $(TEST_VENV)