Port 22
ListenAddress 127.0.0.1
PermitEmptyPasswords yes
PasswordAuthentication yes
PubkeyAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
UsePAM no
ClientAliveInterval 0
ClientAliveCountMax 0
X11Forwarding no
AllowTcpForwarding no
PermitTunnel no
PrintMotd no
